/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DraggablePanel: typeof import('./../src/components/DraggablePanel.vue')['default']
    DragPreview: typeof import('./../src/components/DragPreview.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    NavigatorView: typeof import('./../src/components/NavigatorView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideListPanel: typeof import('./../src/components/SlideListPanel.vue')['default']
  }
}
